on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2022, windows-2019]
        zig: [0.13.0, 0.12.0]
    runs-on: ${{ matrix.os }}
    name: Build and Test    
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig }}
      - id: build-and-test
        run: zig build test
        continue-on-error: true
      - uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: build-and-test-${{matrix.os}}-${{ matrix.zig }}
          LABEL: test-${{matrix.os}}-${{ matrix.zig }}
          STATUS: ${{ steps.build-and-test.outcome == 'failure' && 'failing' || 'passing' }}
          COLOR: ${{ steps.build-and-test.outcome == 'failure' && 'FF0000' || '00FF00' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
