on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2022, windows-2019]
        zig: [master, 0.13.0, 0.12.0]
    runs-on: ${{ matrix.os }}
    name: Build and Test    
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig }}
      - run: zig build test
