on: [push]

jobs:
  test:
    runs-on: windows-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
        with:
          version: 0.13.0
      - uses: mlugg/setup-zig@v1
      - run: zig build test
