on: [push]

jobs:
  test:
    name: Build and Test    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2022, windows-2019]
        zig: [0.13.0, 0.12.0]
    uses: tu7q/echo-server/.github/workflows/test_and_badge.yml@main
    with:
      os: ${{ matrix.os}}
      zig: ${{ matrix.zig }}
    secrets: inherit
